export { default as logo} from './logo.svg'
export { default as search} from './search.svg'
export { default as basket} from './basket.svg'
export { default as login} from './login.svg'
export { default as plant1} from './plant1.png'
export { default as plant2} from './plant2.png'